# PROVENANCE -- committed 2026-09-13 under OPEN-ITEMS.md item R-a.
#
# Produced: reports/r7-hazard-miss-rate.md
#           the hazard-miss counts and the false-alarm counts.
#           [2026-09-23] Regenerated post-df35fd5 on 5/10/20/40: 6/19, 1/3, 4/38
#           with false alarms 65, 5, 54. SUPERSEDED (pre-df35fd5, kept for the
#           record): 8/19, 0/3, 4/38.
# Run:      VRGRID_DATA_ROOT=C:/KITTI/dataset \
#             python reports/harnesses/r7_hazard_miss.py
#
# Measurement only. Reads the shipping code; changes nothing in src/.
"""R7 -- hazard miss rate with the correct denominator. MEASUREMENT ONLY.

    miss rate = |truly non-drivable AND map says drivable| / |truly non-drivable|

"Truly" = M*, via costmap_from_reference. "Map says" = costmap_from_gridmap.
Both on the same planning lattice, restricted to the common support, which is
exactly how eq. (23) pairs them -- so this is a like-for-like verdict
comparison, not a fill-rate measurement.

Gated on reproducing a known-good published number first: if the M* build is
wrong the miss rate is meaningless, and a wrong M* still produces a
confident-looking number.
"""
import sys

import numpy as np
from vrgrid.eval import harness, metrics, reference_map
from vrgrid.eval.plan_regret import (
    IMPASSABLE_BITS,
    common_support,
    costmap_from_gridmap,
    costmap_from_reference,
)

PLAN_BEHIND_M, PLAN_N, PLAN_Y0_M = -11.0, 44, -5.5
# [RE-BASELINED 2026-09-23] Previous values, kept in the record rather than
# overwritten: {"00": 2.73, "07": 1.76, "08": 1.16}. Seq 07 moved 1.7747 ->
# 1.8660 at df35fd5, which made `_compared`'s `serves` test route cells using
# the ring windows that EXIST rather than idealised ones. That recovered 324
# previously-dropped ring-0 cells whose implied RMS is ~10.46 cm against a bulk
# of 1.77, which accounts for the whole +5.14%; 08 and 00 moved -0.02% and
# -0.14%. The old number was not more accurate -- it excluded the hardest cells.
# Evidence: reports/rmse-baseline-investigation-2026-09-23.md. Corroborated by
# docs/known-limitations.md, regenerated by df35fd5 itself, which already
# publishes r0 RMSE 1.87 for seq 07.
# ⚑ CONFIRMED BY EVIDENCE, NOT YET BY THE AUTHOR. Shrestha has not confirmed the
#   ring-0 effect was intended. If he says it was not, this is a live
#   re-investigation, not a settled matter, and these constants revert.
# The 5% tolerance below is UNCHANGED: it caught a real change and was correctly
# red for six days.
BASELINE_R0 = {"00": 2.73, "07": 1.87, "08": 1.17}   # known-limitations 2b


def build(seq, frames, sched_name):
    ref = reference_map.build_from_scans(harness.real_scans(seq, max_frames=frames))
    gm = harness.build_gridmap(harness.load(sched_name))
    harness.run_sequence(gm, harness.real_scans(seq, max_frames=frames))
    return ref, gm


def gate(seq, frames, ref, gm):
    """Refuse to report anything if M* does not reproduce the published RMSE."""
    r0 = metrics.height_rmse_per_ring(gm, ref)[0]
    want = BASELINE_R0.get(seq)
    # 5% tolerance, deliberately. PR #31 changed _ring_cells to filter on
    # ring_of(centre)==ring, so known-limitations 2b is legitimately stale --
    # eval_synthetic.py --seq 07 prints 1.78 today against the doc's 1.76
    # (1.1% apart). A ground-mask-less M*, the failure this gate exists to
    # catch, reads 22.10 cm on seq 07 -- an order of magnitude out. 5% passes
    # the first and catches the second.
    rel = abs(r0 - want) / want if want else float("nan")
    ok = want is not None and rel < 0.05
    print(f"  [gate] ring-0 RMSE {r0:.4f} cm vs doc {want if want else '--'} "
          f"({rel*100:.1f}% apart)  {'OK' if ok else '*** OUT OF TOLERANCE ***'}")
    if want is not None and not ok:
        sys.exit("gate failed -- M* is not trustworthy; nothing below would be either")
    return r0


def hazard_miss(seq, frames, sched_name):
    print(f"\n=== seq {seq}, {frames} frames, schedule {sched_name} ===")
    ref, gm = build(seq, frames, sched_name)
    gate(seq, frames, ref, gm)

    vx, vy = harness.final_vehicle_xy(seq, frames)
    x0, y0 = vx + PLAN_BEHIND_M, vy + PLAN_Y0_M
    star = costmap_from_reference(ref, x0, y0, PLAN_N, PLAN_N)
    mine = costmap_from_gridmap(gm, x0, y0, PLAN_N, PLAN_N, vehicle_xy_m=(vx, vy))

    mask = common_support(star, mine)

    # ⚑ NOT restrict(): it constructs CostMap without `trav`, which then
    #   defaults to None, so restrict(x).trav is None and the bitfield is
    #   gone. Mask the boolean verdicts directly instead -- same cells, and
    #   `trav` survives. (Latent defect in restrict(); no live caller hits it,
    #   because --confound reads low_confidence() off UNRESTRICTED maps.)
    truth_bad_full = (np.asarray(star.trav) & IMPASSABLE_BITS) != 0
    mine_bad_full = (np.asarray(mine.trav) & IMPASSABLE_BITS) != 0
    truth_bad = truth_bad_full[mask]
    mine_bad = mine_bad_full[mask]

    n_cells = int(truth_bad.size)
    n_truth_bad = int(truth_bad.sum())
    miss = truth_bad & ~mine_bad          # truly bad, we called it drivable
    false_alarm = ~truth_bad & mine_bad   # truly fine, we called it a hazard
    n_miss, n_fa = int(miss.sum()), int(false_alarm.sum())

    print(f"  cells in common support        {n_cells:,}")
    print(f"  truly NON-drivable (M*)        {n_truth_bad:,}"
          f"   ({n_truth_bad/max(n_cells,1)*100:.2f}% of support)")
    print(f"  map called drivable            {int((~mine_bad).sum()):,}")
    print(f"  MISSES (bad, called drivable)  {n_miss:,}")
    print(f"  false alarms (fine, called bad){n_fa:>8,}")
    if n_truth_bad:
        print(f"  >>> HAZARD MISS RATE           {n_miss/n_truth_bad*100:.2f}%"
              f"   ({n_miss}/{n_truth_bad})")
        print(f"      hazard recall              {(1-n_miss/n_truth_bad)*100:.2f}%")
    else:
        print("  >>> HAZARD MISS RATE           UNDEFINED -- M* has zero "
              "non-drivable cells in this window; the denominator is 0")
    return dict(seq=seq, frames=frames, sched=sched_name, cells=n_cells,
                truth_bad=n_truth_bad, miss=n_miss, fa=n_fa)


if __name__ == "__main__":
    rows = []
    for seq in ("07", "08", "00"):
        for sched in ("5/10/20/40", "5/10/50"):
            try:
                rows.append(hazard_miss(seq, 40, sched))
            except SystemExit:
                raise
            except Exception as e:
                print(f"  FAILED seq {seq} {sched}: {type(e).__name__}: {e}")
    print("\n=== SUMMARY ===")
    print(f"{'seq':>4} {'schedule':>11} {'support':>9} {'truly bad':>10} "
          f"{'miss':>6} {'miss rate':>10} {'false alarm':>12}")
    for r in rows:
        rate = f"{r['miss']/r['truth_bad']*100:.2f}%" if r["truth_bad"] else "UNDEF"
        print(f"{r['seq']:>4} {r['sched']:>11} {r['cells']:>9,} {r['truth_bad']:>10,} "
              f"{r['miss']:>6,} {rate:>10} {r['fa']:>12,}")
